matrix:
    include:
       - language: julia
         julia: 0.4
         os: linux
         dist: trusty
         sudo: false         
       - language: julia
         julia: 0.5
         os: linux
         dist: trusty
         sudo: false         
       - language: julia
         julia: 0.6 
         os: linux
         dist: trusty
         sudo: false         
       - language: julia
         julia: 0.5
         os: linux
       - language: julia
         julia: 0.4
         os: osx
       - language: julia
         julia: 0.5
         os: osx
       - language: julia
         julia: 0.6 
         os: osx
notifications:
    email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CairoScript")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
 